version: '3'
services:
  backend:
    build: ../backend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:80

  frontend:
    build: .
    container_name: frontend
    ports:
      - "8080:80"
    links:
      - backend